#. docker build -t rffmpeg-test .

version: '3.8'
services:
  rffmpeg-test:
    image: rffmpeg-test
    container_name: rffmpeg-test
    environment:
      - SSH_USERS=dockerlimited:1027:65536 #username/group should match from the media server
      - SSH_GROUPS=dockergroup:65536
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - path/to/id_rsa.pub:/etc/authorized_keys/dockerlimited:z
      - media:/media
      - cache:/cache
      - config:/config:z
    ports:
      - 22:22
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  jellyfin_media:
    driver: local
    driver_opts:
      type: cifs
      o: username=username,password=pass,addr=<media server ip>,ro
      device: //<media server ip>/data/media
  jellyfin_cache:
    driver: local
    driver_opts:
      type: cifs
      o: username=username,password=pass,addr=<media server ip>,file_mode=0777,dir_mode=0777
      device: //<media server ip>/docker/jellyfin/cache
  jellyfin_config:
    driver: local
    driver_opts:
      type: cifs
      o: username=username,password=pass,addr=<media server ip>,file_mode=0777,dir_mode=0777
      device: //<media server ip>/docker/jellyfin/config